import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('quick installer lifecycle scenario ordering', () => {
  it('isolates session and uninstall scenarios from the preceding warm-start state', () => {
    const source = readFileSync(resolve('e2e/specs/provisioning-success.installer.e2e.ts'), 'utf8')
    const firstScenario = source.indexOf("it('installs the desktop shell")
    const secondScenario = source.indexOf("it('creates two sessions")
    const thirdScenario = source.indexOf("it('默认卸载")
    const first = source.slice(firstScenario, secondScenario)
    const second = source.slice(secondScenario, thirdScenario)
    const third = source.slice(thirdScenario)
    const warmTiming = first.indexOf('const warmTiming')
    const timingOutput = first.indexOf('process.stdout.write')
    const warmQuit = first.indexOf('await desktop.quit()', timingOutput)

    expect(firstScenario).toBeGreaterThan(-1)
    expect(secondScenario).toBeGreaterThan(firstScenario)
    expect(thirdScenario).toBeGreaterThan(secondScenario)
    expect(warmTiming).toBeGreaterThan(-1)
    expect(timingOutput).toBeGreaterThan(warmTiming)
    expect(warmQuit).toBeGreaterThan(timingOutput)
    const cleanInstall = second.indexOf('const installation = await installer.installClean()')
    const coldLaunch = second.indexOf('await desktop.launch(installation.appBinary)')
    const coldReady = second.indexOf('await desktop.waitForWorkbench(180_000)')
    const firstConversation = second.indexOf('await desktop.createConversation')
    const firstQuit = second.indexOf('await desktop.quit()', firstConversation)
    const warmLaunch = second.indexOf('await desktop.launch(installation.appBinary)', firstQuit)
    const warmReady = second.indexOf('await desktop.waitForWorkbench(8_000)', warmLaunch)
    const uninstallInstall = third.indexOf('const installation = await installer.installClean()')
    const uninstallLaunch = third.indexOf('await desktop.launch(installation.appBinary)')
    const uninstallReady = third.indexOf('await desktop.waitForWorkbench(180_000)')
    const runtimeIdentity = third.indexOf('const recordedRuntimeIdentity = await installer.recordRuntimeIdentity')
    const uninstallQuit = third.indexOf('await desktop.quit()', runtimeIdentity)
    const uninstall = third.indexOf("await installer.uninstall('preserve-all')")

    expect(cleanInstall).toBeGreaterThan(-1)
    expect(coldLaunch).toBeGreaterThan(cleanInstall)
    expect(coldReady).toBeGreaterThan(coldLaunch)
    expect(firstConversation).toBeGreaterThan(coldReady)
    expect(firstQuit).toBeGreaterThan(firstConversation)
    expect(warmLaunch).toBeGreaterThan(firstQuit)
    expect(warmReady).toBeGreaterThan(warmLaunch)
    expect(uninstallInstall).toBeGreaterThan(-1)
    expect(uninstallLaunch).toBeGreaterThan(uninstallInstall)
    expect(uninstallReady).toBeGreaterThan(uninstallLaunch)
    expect(runtimeIdentity).toBeGreaterThan(uninstallReady)
    expect(uninstallQuit).toBeGreaterThan(runtimeIdentity)
    expect(uninstall).toBeGreaterThan(uninstallQuit)
  })
})
