/** Isolated native window presenting model diagnostics: test, list, select. */

import type { BrowserWindow } from 'electron'
import { fileURLToPath } from 'node:url'
import {
  auxiliaryWindowChromeOptions,
  auxiliaryWindowHasCustomFrame,
} from './auxiliary-window-options.ts'
import { revealApplication } from './electron-reveal.ts'
import { createDesktopLocalWindow } from './local-window-policy.ts'
import type { DesktopLocale } from './runtime.ts'
import { desktopModelDiagnosticsCopy } from './model-diagnostics-copy.ts'

const MODEL_DIAGNOSTICS_SCHEME = 'dsh-model-diagnostics:'
const MODEL_DIAGNOSTICS_DOCUMENT = fileURLToPath(new URL('./native-ui/model-diagnostics.html', import.meta.url))
const PUSH_INTERVAL_MS = 2_000

export interface ModelDiagnosticsAction {
  readonly action: 'probe' | 'select' | 'close'
  readonly model?: string
}

/** Parse only the actions generated by the local diagnostics document. */
export function parseModelDiagnosticsAction(href: string): ModelDiagnosticsAction | undefined {
  let url: URL
  try { url = new URL(href) } catch { return undefined }
  if (url.protocol !== MODEL_DIAGNOSTICS_SCHEME
    || url.username !== '' || url.password !== '' || url.port !== ''
    || url.pathname !== '' || url.hash !== '') return undefined
  const keys = [...url.searchParams.keys()]
  const action = url.hostname
  if (action === 'probe' || action === 'close') {
    return keys.length === 0 ? { action } : undefined
  }
  if (action !== 'select' || keys.length !== 1 || keys[0] !== 'model') return undefined
  const model = url.searchParams.get('model')
  if (model === null || model.length === 0 || Buffer.byteLength(model, 'utf8') > 200) return undefined
  return { action, model }
}

/** Own one isolated diagnostics window; repeated opens focus the same instance. */
export class ModelDiagnosticsWindow {
  private window: BrowserWindow | undefined
  private pushTimer: NodeJS.Timeout | undefined

  open(locale: DesktopLocale): void {
    const existing = this.window
    if (existing !== undefined && !existing.isDestroyed()) {
      revealApplication(existing)
      return
    }
    const copy = desktopModelDiagnosticsCopy(locale)
    const window = createDesktopLocalWindow({
      partition: 'dsh-model-diagnostics',
      title: copy.title,
      ...auxiliaryWindowChromeOptions(),
      width: 460,
      height: 560,
      minWidth: 420,
      minHeight: 500,
      resizable: false,
      show: false,
      autoHideMenuBar: true,
      backgroundColor: '#202124',
    })
    this.window = window
    window.accessibleTitle = copy.title
    window.removeMenu()
    const navigate = (event: Electron.Event, href: string): void => {
      const action = parseModelDiagnosticsAction(href)
      event.preventDefault()
      if (action !== undefined) void this.handleAction(action)
    }
    window.webContents.on('will-navigate', navigate)
    window.webContents.on('will-redirect', navigate)
    window.once('ready-to-show', () => {
      if (this.window === window && !window.isDestroyed()) revealApplication(window)
    })
    window.on('closed', () => {
      if (this.window === window) {
        this.window = undefined
        if (this.pushTimer !== undefined) {
          clearInterval(this.pushTimer)
          this.pushTimer = undefined
        }
      }
    })
    void window.loadFile(MODEL_DIAGNOSTICS_DOCUMENT, {
      query: {
        locale,
        platform: process.platform,
        frame: String(auxiliaryWindowHasCustomFrame()),
      },
    }).catch(() => {
      if (this.window === window) window.close()
    })
    if (this.pushTimer === undefined) {
      this.pushTimer = setInterval(() => void this.push(), PUSH_INTERVAL_MS)
    }
    void this.push()
  }

  close(): void {
    const window = this.window
    this.window = undefined
    if (this.pushTimer !== undefined) {
      clearInterval(this.pushTimer)
      this.pushTimer = undefined
    }
    if (window !== undefined && !window.isDestroyed()) window.close()
  }

  private async push(): Promise<void> {
    const window = this.window
    if (window === undefined || window.isDestroyed()) return
    let state: unknown
    try {
      const { getDesktopModelDiagnosticsState } = await import('./model-diagnostics-state.ts')
      state = await getDesktopModelDiagnosticsState()
    } catch {
      return
    }
    const message = JSON.stringify(state)
    await window.webContents.executeJavaScript(
      `window.dispatchEvent(new CustomEvent('dsh-model-diagnostics-state', { detail: ${message} }))`,
      true,
    ).catch(() => {})
  }

  private async handleAction(action: ModelDiagnosticsAction): Promise<void> {
    const window = this.window
    if (window === undefined || window.isDestroyed()) return
    if (action.action === 'close') {
      this.close()
      return
    }
    let payload: unknown
    try {
      const state = await import('./model-diagnostics-state.ts')
      payload = action.action === 'probe'
        ? await state.probeDesktopModels()
        : await state.selectDesktopModel(action.model ?? '')
    } catch (cause) {
      payload = { ok: false, error: cause instanceof Error ? cause.message : String(cause) }
    }
    const message = JSON.stringify(payload)
    await window.webContents.executeJavaScript(
      `window.dispatchEvent(new CustomEvent('dsh-model-diagnostics-result', { detail: ${message} }))`,
      true,
    ).catch(() => {})
    await this.push()
  }
}
