/** Isolated native window presenting the remote-control QR pairing. */

import type { BrowserWindow } from 'electron'
import { fileURLToPath } from 'node:url'
import QRCode from 'qrcode'
import {
  auxiliaryWindowChromeOptions,
  auxiliaryWindowHasCustomFrame,
} from './auxiliary-window-options.ts'
import { revealApplication } from './electron-reveal.ts'
import { createDesktopLocalWindow } from './local-window-policy.ts'
import type { DesktopLocale, RemotePairingWindowOptions } from './runtime.ts'
import { desktopRemotePairingCopy } from './remote-pairing-copy.ts'
import type { DesktopRemoteRelaySnapshot } from './remote-relay.ts'

const REMOTE_PAIRING_SCHEME = 'dsh-remote-pairing:'
const REMOTE_PAIRING_DOCUMENT = fileURLToPath(new URL('./native-ui/remote-pairing.html', import.meta.url))
const PUSH_INTERVAL_MS = 2_000
const MAX_LINK_BYTES = 8_192

/** One state push rendered by the local pairing document. */
export interface RemotePairingWindowState {
  readonly state: DesktopRemoteRelaySnapshot['state']
  readonly relayOrigin: string | null
  readonly pairUrl: string | null
  readonly qrSvg: string | null
  readonly error: string | null
  /** True while a phone page has polled recently — same signal as the sidebar glyph. */
  readonly connected: boolean
}

export interface RemotePairingAction {
  readonly action: 'copy' | 'regenerate' | 'enable' | 'close'
  readonly link?: string
}

/** Parse only the actions generated by the local pairing document. */
export function parseRemotePairingAction(href: string): RemotePairingAction | undefined {
  let url: URL
  try { url = new URL(href) } catch { return undefined }
  if (url.protocol !== REMOTE_PAIRING_SCHEME
    || url.username !== '' || url.password !== '' || url.port !== ''
    || url.pathname !== '' || url.hash !== '') return undefined
  const keys = [...url.searchParams.keys()]
  const action = url.hostname
  if (action === 'regenerate' || action === 'enable' || action === 'close') {
    return keys.length === 0 ? { action } : undefined
  }
  if (action !== 'copy' || keys.length !== 1 || keys[0] !== 'link') return undefined
  const link = url.searchParams.get('link')
  if (link === null || Buffer.byteLength(link, 'utf8') > MAX_LINK_BYTES) return undefined
  return { action, link }
}

async function qrSvgFor(pairUrl: string): Promise<string | null> {
  try {
    return await QRCode.toString(pairUrl, {
      type: 'svg',
      margin: 1,
      width: 232,
      errorCorrectionLevel: 'M',
    })
  } catch {
    return null
  }
}

/** Own one isolated pairing window; repeated opens focus the same instance. */
export class RemotePairingWindow {
  private window: BrowserWindow | undefined
  private pushTimer: NodeJS.Timeout | undefined
  private loaded = false
  private latest: RemotePairingWindowState | null = null
  private clipboard = ''

  constructor(private readonly options: RemotePairingWindowOptions) {}

  open(): void {
    const existing = this.window
    if (existing !== undefined && !existing.isDestroyed()) {
      revealApplication(existing)
      return
    }
    const locale: DesktopLocale = this.options.locale()
    const copy = desktopRemotePairingCopy(locale)
    const window = createDesktopLocalWindow({
      partition: 'dsh-remote-pairing',
      title: copy.title,
      ...auxiliaryWindowChromeOptions(),
      width: 460,
      height: 620,
      minWidth: 420,
      minHeight: 560,
      resizable: false,
      show: false,
      autoHideMenuBar: true,
      backgroundColor: '#202124',
    })
    this.window = window
    this.loaded = false
    this.latest = null
    window.accessibleTitle = copy.title
    window.removeMenu()
    const navigate = (event: Electron.Event, href: string): void => {
      const action = parseRemotePairingAction(href)
      event.preventDefault()
      if (action !== undefined) void this.handleAction(action)
    }
    window.webContents.on('will-navigate', navigate)
    window.webContents.on('will-redirect', navigate)
    window.once('ready-to-show', () => {
      if (this.window === window && !window.isDestroyed()) revealApplication(window)
    })
    window.webContents.once('did-finish-load', () => {
      if (this.window !== window) return
      this.loaded = true
      this.flush()
    })
    window.on('closed', () => {
      if (this.window === window) {
        this.window = undefined
        if (this.pushTimer !== undefined) {
          clearInterval(this.pushTimer)
          this.pushTimer = undefined
        }
      }
    })
    void window.loadFile(REMOTE_PAIRING_DOCUMENT, {
      query: {
        locale,
        platform: process.platform,
        frame: String(auxiliaryWindowHasCustomFrame()),
      },
    }).catch(() => {
      if (this.window === window) window.close()
    })
    if (this.pushTimer === undefined) {
      this.pushTimer = setInterval(() => void this.collect(), PUSH_INTERVAL_MS)
    }
    void this.collect()
  }

  close(): void {
    const window = this.window
    this.window = undefined
    if (this.pushTimer !== undefined) {
      clearInterval(this.pushTimer)
      this.pushTimer = undefined
    }
    if (window !== undefined && !window.isDestroyed()) window.close()
  }

  /** The last link this window copied, kept for focused tests. */
  copiedLink(): string {
    return this.clipboard
  }

  private async collect(): Promise<void> {
    const window = this.window
    if (window === undefined || window.isDestroyed()) return
    const snapshot = await this.options.snapshot()
    this.latest = {
      state: snapshot.state,
      relayOrigin: snapshot.relayOrigin,
      pairUrl: snapshot.pairUrl,
      qrSvg: snapshot.pairUrl === null ? null : await qrSvgFor(snapshot.pairUrl),
      error: snapshot.error,
      connected: snapshot.connected,
    }
    this.flush()
  }

  private flush(): void {
    const window = this.window
    if (!this.loaded || window === undefined || window.isDestroyed() || this.latest === null) return
    const message = JSON.stringify(this.latest)
    void window.webContents.executeJavaScript(
      `window.dispatchEvent(new CustomEvent('dsh-remote-pairing-state', { detail: ${message} }))`,
      true,
    ).catch(() => {})
  }

  private async handleAction(action: RemotePairingAction): Promise<void> {
    if (action.action === 'close') {
      this.close()
      return
    }
    if (action.action === 'copy') {
      const { clipboard } = await import('electron')
      clipboard.writeText(action.link ?? '')
      this.clipboard = action.link ?? ''
      const window = this.window
      if (window !== undefined && !window.isDestroyed()) {
        void window.webContents.executeJavaScript(
          "window.dispatchEvent(new CustomEvent('dsh-remote-pairing-copied'))",
          true,
        ).catch(() => {})
      }
      return
    }
    if (action.action === 'enable') {
      this.options.enable?.()
      await this.collect()
      return
    }
    this.options.regenerate?.()
    await this.collect()
  }
}
